config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects
  resources :meetings
  resources :milestones
  resources :tasks
  resources :themes

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :project
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :meetings
  has_many :milestones
  has_many :tasks, through: :themes
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :tasks
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :company)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/milestone_helper.rb
module MilestoneHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.text_field :title, placeholder: "Project Name" %>
  <%= f.text_field :company, placeholder: "Company" %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 class="todo_list_title">Edit Project</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', projects_path %>
</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to project.title, project %></h2>
    <p class="todo_list_sub_title"><%= project.company %></p>
    <p class="todo_list_sub_title"><%#= project.meetings.first.appointment %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Project", new_project_path %>
</div>

app/views/projects/new.html.erb
<h1 class="todo_list_title">New Project</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @project.title %></h2>
<p class="todo_list_sub_title"><%= @project.company %></p>

<div id="todo_items_wrapper">
	<%#= render @project.milestones %>
	<div id="form">
		<%#= render "todo_items/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_project_path(@project) %> |
	<%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', projects_path %>
</div>